#!/bin/false

# Copyright (c) 2022 Vít Labuda. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
# following conditions are met:
#  1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
#     disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
#     following disclaimer in the documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
#     products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


import os
import os.path
import sys
if "DATALIDATOR_TESTS_AUTOPATH" in os.environ:
    __TESTS_DIR = os.path.dirname(os.path.realpath(__file__))
    __MODULE_DIR = os.path.realpath(os.path.join(__TESTS_DIR, "../.."))
    if __TESTS_DIR not in sys.path:
        sys.path.insert(0, __TESTS_DIR)
    if __MODULE_DIR not in sys.path:
        sys.path.insert(0, __MODULE_DIR)

import theoretical_testutils
import pytest
import re
import datetime
import ipaddress
import urllib.parse
import uuid
from test_014_string_blueprint import StringableObject, ExceptionRaisingStringableObject
from datalidator.blueprints.impl.UnixFilesystemPathBlueprint import UnixFilesystemPathBlueprint
from datalidator.blueprints.exc.InvalidInputDataExc import InvalidInputDataExc
from datalidator.blueprints.exc.InputDataTypeNotInAllowlistExc import InputDataTypeNotInAllowlistExc
from datalidator.filters.impl.UnixFilesystemPathAddTrailingSlashFilter import UnixFilesystemPathAddTrailingSlashFilter
from datalidator.filters.impl.UnixFilesystemPathStripTrailingSlashesFilter import UnixFilesystemPathStripTrailingSlashesFilter
from datalidator.filters.impl.StringControlAndSeparatorCharacterFilter import StringControlAndSeparatorCharacterFilter
from datalidator.filters.impl.StringDeduplicateWhitespaceFilter import StringDeduplicateWhitespaceFilter
from datalidator.filters.impl.StringUnicodeNormalizeFilter import StringUnicodeNormalizeFilter
from datalidator.filters.impl.StringUnifyWhitespaceFilter import StringUnifyWhitespaceFilter
from datalidator.validators.impl.UnixFilesystemPathContainsOnlyFilenameValidator import UnixFilesystemPathContainsOnlyFilenameValidator
from datalidator.validators.impl.UnixFilesystemPathIsAbsoluteValidator import UnixFilesystemPathIsAbsoluteValidator
from datalidator.validators.impl.UnixFilesystemPathIsRelativeValidator import UnixFilesystemPathIsRelativeValidator
from datalidator.validators.impl.SequenceMinimumLengthValidator import SequenceMinimumLengthValidator
from datalidator.validators.impl.SequenceMaximumLengthValidator import SequenceMaximumLengthValidator
from datalidator.validators.impl.StringContainsNoControlOrSeparatorCharactersValidator import StringContainsNoControlOrSeparatorCharactersValidator
from datalidator.validators.impl.StringIsOnlySingleLineValidator import StringIsOnlySingleLineValidator
from datalidator.validators.impl.StringMatchesRegexValidator import StringMatchesRegexValidator
from datalidator.validators.exc.DataValidationFailedExc import DataValidationFailedExc


__UNIX_FILESYSTEM_PATH_TEST_SUITE = (
    (UnixFilesystemPathBlueprint(), (
        ("", InvalidInputDataExc),
        (" " * 50, InvalidInputDataExc),
        ("\n", InvalidInputDataExc),
        ("\t", InvalidInputDataExc),
        ("    \t\t   \v\v\f\n\r   \t\t\x85\x1c\x85  ", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test.txt", "test.txt"),
        ("test\x01.txt", "test\x01.txt"),
        ("test\uffff.txt", "test\uffff.txt"),
        ("test🤍.txt", "test🤍.txt"),
        ("\x00test.txt", InvalidInputDataExc),
        ("test\x00.txt", InvalidInputDataExc),
        ("test.txt\x00", InvalidInputDataExc),
        ("/home/test/abcdef", "/home/test/abcdef"),
        ("\x00/home/test/abcdef", InvalidInputDataExc),
        ("/home/test/abc\x00def", InvalidInputDataExc),
        ("/home/test/abcdef\x00", InvalidInputDataExc),
        ("\n\r   \t/home/test/abc\x00def   \v\u2028\f", InvalidInputDataExc),
        ("testdir/test.txt", "testdir/test.txt"),
        ("testdir//test.txt", "testdir/test.txt"),
        ("testdir///test.txt", "testdir/test.txt"),
        ("/home/test/image.jpg", "/home/test/image.jpg"),
        ("///home//test/image.jpg", "/home/test/image.jpg"),
        ("//home////////////////////test/////image.jpg", "/home/test/image.jpg"),
        ("\u2029\t   \n\r\r  testdir/test.txt\u2029\x85  \x1e\u2028", "testdir/test.txt"),
        ("\u2029\t   \n\r\r  testdir//test.txt\u2029\x85  \x1e\u2028", "testdir/test.txt"),
        ("\u2029\t   \n\r\r  testdir///test.txt\u2029\x85  \x1e\u2028", "testdir/test.txt"),
        ("\u2029\t   \n\r\r  /home/test/image.jpg\u2029\x85  \x1e\u2028", "/home/test/image.jpg"),
        ("\u2029\t   \n\r\r  ///home//test/image.jpg\u2029\x85  \x1e\u2028", "/home/test/image.jpg"),
        ("\u2029\t   \n\r\r  //home////////////////////test/////image.jpg\u2029\x85  \x1e\u2028", "/home/test/image.jpg"),
        ("\u2029\t   \n\r\r  //home////////////////////test/////image.jpg\u2029\x85  \x00\x1e\u2028", InvalidInputDataExc),
        ("\u2029\t   \n\r\r  //home//////////////\x00//////test/////image.jpg\u2029\x85  \x1e\u2028", InvalidInputDataExc),
        ("hello.txt", "hello.txt"),
        (" hello.txt\r\n", "hello.txt"),
        (" hell\x00o.txt\r\n", InvalidInputDataExc),
        ("dir/hello.txt", "dir/hello.txt"),
        ("dir///hello.txt", "dir/hello.txt"),
        (" dir/hello.txt\r\n", "dir/hello.txt"),
        (" dir///hello.txt\r\n", "dir/hello.txt"),
        (" dir///hell\x00o.txt\r\n", InvalidInputDataExc),
        ("topdir/middledir/bottomdir/dir/hello.txt", "topdir/middledir/bottomdir/dir/hello.txt"),
        ("topdir///middledir//bottomdir//dir////hello.txt", "topdir/middledir/bottomdir/dir/hello.txt"),
        (" topdir/middledir/bottomdir/dir/hello.txt\r\n", "topdir/middledir/bottomdir/dir/hello.txt"),
        (" topdir///middledir//bottomdir//dir////hello.txt\r\n", "topdir/middledir/bottomdir/dir/hello.txt"),
        (" topdir///middledir//bottom\x00dir//dir////hello.txt\r\n", InvalidInputDataExc),
        ("/home/test/Downloads/program/topdir/middledir/bottomdir/dir/hello.txt", "/home/test/Downloads/program/topdir/middledir/bottomdir/dir/hello.txt"),
        ("///home/test//Downloads///////program//topdir/middledir//bottomdir/dir/////hello.txt", "/home/test/Downloads/program/topdir/middledir/bottomdir/dir/hello.txt"),
        (" /home/test/Downloads/program/topdir/middledir/bottomdir/dir/hello.txt\r\n", "/home/test/Downloads/program/topdir/middledir/bottomdir/dir/hello.txt"),
        (" ///home/test//Downloads///////program//topdir/middledir//bottomdir/dir/////hello.txt\r\n", "/home/test/Downloads/program/topdir/middledir/bottomdir/dir/hello.txt"),
        (" ///home/test//Downloads////\x00///program//topdir/middledir//bottomdir/dir/////hello.txt\r\n", InvalidInputDataExc),
        ("\n\rřeřicha.txt   ", "řeřicha.txt"),
        ("\n\rfiles/řeřicha.txt   ", "files/řeřicha.txt"),
        ("\n\r/home/test/řeřicha.txt   ", "/home/test/řeřicha.txt"),
        ("\n\r/home/test/ře\x00řicha.txt   ", InvalidInputDataExc),
        ("\u2029\n\r  Příliš žluťoučký kůň úpěl ďábelské ódy.txt \v\t\f\x85", "Příliš žluťoučký kůň úpěl ďábelské ódy.txt"),
        ("\u2029\n\r  files/Příliš žluťoučký kůň úpěl ďábelské ódy.txt \v\t\f\x85", "files/Příliš žluťoučký kůň úpěl ďábelské ódy.txt"),
        ("\u2029\n\r  /home/test/Příliš žluťoučký kůň úpěl ďábelské ódy.txt \v\t\f\x85", "/home/test/Příliš žluťoučký kůň úpěl ďábelské ódy.txt"),
        ("\u2029\n\r  /home/test/Příliš žluťoučký kůň úpěl ďábe\x00lské ódy.txt \v\t\f\x85", InvalidInputDataExc),
        (".", "."),
        ("..", ".."),
        ("./", "./"),
        ("../", "../"),
        (".///", "./"),
        ("..///", "../"),
        ("\n\n\n   .\t\v\u2028", "."),
        ("\n\n\n   ..\t\v\u2028", ".."),
        ("\n\n\n   ./\t\v\u2028", "./"),
        ("\n\n\n   ../\t\v\u2028", "../"),
        ("\n\n\n   .///\t\v\u2028", "./"),
        ("\n\n\n   ..///\t\v\u2028", "../"),
        (None, InputDataTypeNotInAllowlistExc),
        (True, InputDataTypeNotInAllowlistExc),
        (False, InputDataTypeNotInAllowlistExc),
        (-1, InputDataTypeNotInAllowlistExc),
        (0, InputDataTypeNotInAllowlistExc),
        (1, InputDataTypeNotInAllowlistExc),
        (-1.5, InputDataTypeNotInAllowlistExc),
        (-1.0, InputDataTypeNotInAllowlistExc),
        (-0.0, InputDataTypeNotInAllowlistExc),
        (0.0, InputDataTypeNotInAllowlistExc),
        (1.0, InputDataTypeNotInAllowlistExc),
        (1.5, InputDataTypeNotInAllowlistExc),
        (float("inf"), InputDataTypeNotInAllowlistExc),
        (float("nan"), InputDataTypeNotInAllowlistExc),
        (1+2j, InputDataTypeNotInAllowlistExc),
        (b'', InputDataTypeNotInAllowlistExc),
        (b'hello.txt', InputDataTypeNotInAllowlistExc),
        (b'dir/hello.txt', InputDataTypeNotInAllowlistExc),
        (b'/home/test/hello.txt', InputDataTypeNotInAllowlistExc),
        (bytearray(b''), InputDataTypeNotInAllowlistExc),
        (bytearray(b'hello.txt'), InputDataTypeNotInAllowlistExc),
        (bytearray(b'dir/hello.txt'), InputDataTypeNotInAllowlistExc),
        (bytearray(b'/home/test/hello.txt'), InputDataTypeNotInAllowlistExc),
        ([], InputDataTypeNotInAllowlistExc),
        (["test.txt"], InputDataTypeNotInAllowlistExc),
        ({}, InputDataTypeNotInAllowlistExc),
        ({"test.txt": "test.txt"}, InputDataTypeNotInAllowlistExc),
        (str, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject, InputDataTypeNotInAllowlistExc),
        (datetime.datetime.now(), InputDataTypeNotInAllowlistExc),
        (datetime.datetime.now().date(), InputDataTypeNotInAllowlistExc),
        (datetime.datetime.now().time(), InputDataTypeNotInAllowlistExc),
        (ipaddress.ip_address("127.7.8.9"), InputDataTypeNotInAllowlistExc),
        (ipaddress.ip_address("::1"), InputDataTypeNotInAllowlistExc),
        (ipaddress.ip_network("127.0.0.0/8"), InputDataTypeNotInAllowlistExc),
        (ipaddress.ip_network("2001:db8::/64"), InputDataTypeNotInAllowlistExc),
        (urllib.parse.urlparse("https://www.google.com/test?abc=def"), InputDataTypeNotInAllowlistExc),
        (uuid.UUID('{12345678-1234-5678-1234-567812345678}'), InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.TestException(), InputDataTypeNotInAllowlistExc),
        (object(), InputDataTypeNotInAllowlistExc),
        (StringableObject("hello.txt"), InputDataTypeNotInAllowlistExc),
        (StringableObject("dir/hello.txt"), InputDataTypeNotInAllowlistExc),
        (StringableObject("/home/test/dir/hello.txt"), InputDataTypeNotInAllowlistExc),
        (StringableObject(None), InputDataTypeNotInAllowlistExc),
        (StringableObject(theoretical_testutils.EmptyObject()), InputDataTypeNotInAllowlistExc),
        (ExceptionRaisingStringableObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(filters=(UnixFilesystemPathAddTrailingSlashFilter(),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("dir", "dir/"),
        ("dir/", "dir/"),
        ("dir//", "dir/"),
        ("dir///", "dir/"),
        ("dir\uffff", "dir\uffff/"),
        ("dir\uffff/", "dir\uffff/"),
        ("dir\uffff//", "dir\uffff/"),
        ("dir\uffff///", "dir\uffff/"),
        ("dir/Příliš žluťoučký kůň", "dir/Příliš žluťoučký kůň/"),
        ("dir/Příliš žluťoučký kůň/", "dir/Příliš žluťoučký kůň/"),
        ("dir//Příliš žluťoučký kůň//", "dir/Příliš žluťoučký kůň/"),
        ("dir///Příliš žluťoučký kůň///", "dir/Příliš žluťoučký kůň/"),
        ("/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/"),
        ("/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/"),
        ("//home//test//Downloads//dir//Příliš žluťoučký kůň//🤍//", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/"),
        ("///home///test///Downloads///dir///Příliš žluťoučký kůň///🤍///", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/"),
        ("\u2028\x85  \t\f\v \x1c dir\u2029\u202f\n\r\n    ", "dir/"),
        ("\u2028\x85  \t\f\v \x1c dir/\u2029\u202f\n\r\n    ", "dir/"),
        ("\u2028\x85  \t\f\v \x1c dir//\u2029\u202f\n\r\n    ", "dir/"),
        ("\u2028\x85  \t\f\v \x1c dir///\u2029\u202f\n\r\n    ", "dir/"),
        ("\u2028\x85  \t\f\v \x1c dir\uffff\u2029\u202f\n\r\n    ", "dir\uffff/"),
        ("\u2028\x85  \t\f\v \x1c dir\uffff/\u2029\u202f\n\r\n    ", "dir\uffff/"),
        ("\u2028\x85  \t\f\v \x1c dir\uffff//\u2029\u202f\n\r\n    ", "dir\uffff/"),
        ("\u2028\x85  \t\f\v \x1c dir\uffff///\u2029\u202f\n\r\n    ", "dir\uffff/"),
        ("\u2028\x85  \t\f\v \x1c dir/Příliš žluťoučký kůň\u2029\u202f\n\r\n    ", "dir/Příliš žluťoučký kůň/"),
        ("\u2028\x85  \t\f\v \x1c dir/Příliš žluťoučký kůň/\u2029\u202f\n\r\n    ", "dir/Příliš žluťoučký kůň/"),
        ("\u2028\x85  \t\f\v \x1c dir//Příliš žluťoučký kůň//\u2029\u202f\n\r\n    ", "dir/Příliš žluťoučký kůň/"),
        ("\u2028\x85  \t\f\v \x1c dir///Příliš žluťoučký kůň///\u2029\u202f\n\r\n    ", "dir/Příliš žluťoučký kůň/"),
        ("\u2028\x85  \t\f\v \x1c /home/test/Downloads/dir/Příliš žluťoučký kůň/🤍\u2029\u202f\n\r\n    ", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/"),
        ("\u2028\x85  \t\f\v \x1c /home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/\u2029\u202f\n\r\n    ", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/"),
        ("\u2028\x85  \t\f\v \x1c //home//test//Downloads//dir//Příliš žluťoučký kůň//🤍//\u2029\u202f\n\r\n    ", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/"),
        ("\u2028\x85  \t\f\v \x1c ///home///test///Downloads///dir///Příliš žluťoučký kůň///🤍///\u2029\u202f\n\r\n    ", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/"),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(filters=(UnixFilesystemPathStripTrailingSlashesFilter(),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("dir", "dir"),
        ("dir/", "dir"),
        ("dir//", "dir"),
        ("dir///", "dir"),
        ("dir\uffff", "dir\uffff"),
        ("dir\uffff/", "dir\uffff"),
        ("dir\uffff//", "dir\uffff"),
        ("dir\uffff///", "dir\uffff"),
        ("dir/Příliš žluťoučký kůň", "dir/Příliš žluťoučký kůň"),
        ("dir/Příliš žluťoučký kůň/", "dir/Příliš žluťoučký kůň"),
        ("dir//Příliš žluťoučký kůň//", "dir/Příliš žluťoučký kůň"),
        ("dir///Příliš žluťoučký kůň///", "dir/Příliš žluťoučký kůň"),
        ("/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍"),
        ("/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍"),
        ("//home//test//Downloads//dir//Příliš žluťoučký kůň//🤍//", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍"),
        ("///home///test///Downloads///dir///Příliš žluťoučký kůň///🤍///", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍"),
        ("\u2028\x85  \t\f\v \x1c dir\u2029\u202f\n\r\n    ", "dir"),
        ("\u2028\x85  \t\f\v \x1c dir/\u2029\u202f\n\r\n    ", "dir"),
        ("\u2028\x85  \t\f\v \x1c dir//\u2029\u202f\n\r\n    ", "dir"),
        ("\u2028\x85  \t\f\v \x1c dir///\u2029\u202f\n\r\n    ", "dir"),
        ("\u2028\x85  \t\f\v \x1c dir\uffff\u2029\u202f\n\r\n    ", "dir\uffff"),
        ("\u2028\x85  \t\f\v \x1c dir\uffff/\u2029\u202f\n\r\n    ", "dir\uffff"),
        ("\u2028\x85  \t\f\v \x1c dir\uffff//\u2029\u202f\n\r\n    ", "dir\uffff"),
        ("\u2028\x85  \t\f\v \x1c dir\uffff///\u2029\u202f\n\r\n    ", "dir\uffff"),
        ("\u2028\x85  \t\f\v \x1c dir/Příliš žluťoučký kůň\u2029\u202f\n\r\n    ", "dir/Příliš žluťoučký kůň"),
        ("\u2028\x85  \t\f\v \x1c dir/Příliš žluťoučký kůň/\u2029\u202f\n\r\n    ", "dir/Příliš žluťoučký kůň"),
        ("\u2028\x85  \t\f\v \x1c dir//Příliš žluťoučký kůň//\u2029\u202f\n\r\n    ", "dir/Příliš žluťoučký kůň"),
        ("\u2028\x85  \t\f\v \x1c dir///Příliš žluťoučký kůň///\u2029\u202f\n\r\n    ", "dir/Příliš žluťoučký kůň"),
        ("\u2028\x85  \t\f\v \x1c /home/test/Downloads/dir/Příliš žluťoučký kůň/🤍\u2029\u202f\n\r\n    ", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍"),
        ("\u2028\x85  \t\f\v \x1c /home/test/Downloads/dir/Příliš žluťoučký kůň/🤍/\u2029\u202f\n\r\n    ", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍"),
        ("\u2028\x85  \t\f\v \x1c //home//test//Downloads//dir//Příliš žluťoučký kůň//🤍//\u2029\u202f\n\r\n    ", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍"),
        ("\u2028\x85  \t\f\v \x1c ///home///test///Downloads///dir///Příliš žluťoučký kůň///🤍///\u2029\u202f\n\r\n    ", "/home/test/Downloads/dir/Příliš žluťoučký kůň/🤍"),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(filters=(StringControlAndSeparatorCharacterFilter(allowed_characters=" "),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("    \tfile.txt  \r\n", "file.txt"),
        ("    \tPříliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš žluťoučký kůň 🤍.txt  \r\n", "/home/test/Příliš žluťoučký kůň 🤍.txt"),
        ("    \tfi\uffffle.txt  \r\n", "file.txt"),
        ("    \t\uffffPříliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt\uffff  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš\uffff žluťoučký kůň\uffff🤍.txt  \r\n", "/home/test/Příliš žluťoučký kůň🤍.txt"),
        ("    \tfi\n\rle.txt  \r\n", "file.txt"),
        ("    \t\n\rPříliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt\n\r  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš\n\r žluťoučký kůň\n\r🤍.txt  \r\n", "/home/test/Příliš žluťoučký kůň🤍.txt"),
        ("    \tfi\ale.txt  \r\n", "file.txt"),
        ("    \t\aPříliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt\a  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš\a žluťoučký kůň\a🤍.txt  \r\n", "/home/test/Příliš žluťoučký kůň🤍.txt"),
        ("    \tfi\u2060le.txt  \r\n", "file.txt"),
        ("    \t\u2060Příliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt\u2060  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš\u2060 žluťoučký kůň\u2060🤍.txt  \r\n", "/home/test/Příliš žluťoučký kůň🤍.txt"),
        ("    \tfi\u2028le.txt  \r\n", "file.txt"),
        ("    \t\u2028Příliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt\u2028  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš\u2028 žluťoučký kůň\u2028🤍.txt  \r\n", "/home/test/Příliš žluťoučký kůň🤍.txt"),
        ("    \tfi\u2029le.txt  \r\n", "file.txt"),
        ("    \t\u2029Příliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt\u2029  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš\u2029 žluťoučký kůň\u2029🤍.txt  \r\n", "/home/test/Příliš žluťoučký kůň🤍.txt"),
        ("    \tfi\u00a0le.txt  \r\n", "file.txt"),
        ("    \t\u00a0Příliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt\u00a0  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš\u00a0 žluťoučký kůň\u00a0🤍.txt  \r\n", "/home/test/Příliš žluťoučký kůň🤍.txt"),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(filters=(StringDeduplicateWhitespaceFilter(),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("    \tfile.txt  \r\n", "file.txt"),
        ("    \tPříliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš žluťoučký kůň 🤍.txt  \r\n", "/home/test/Příliš žluťoučký kůň 🤍.txt"),
        ("    \tfi\t\r\nle.txt  \r\n", "fi\nle.txt"),
        ("    \tPříliš                       žluťoučký         kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test \u2028\u2029\u202f/file.txt  \r\n", "/home/test\u202f/file.txt"),
        ("    \t///home//test/Příliš     \x1c\x1d\x85\u00a0žluťoučký kůň 🤍.txt  \r\n", "/home/test/Příliš\u00a0žluťoučký kůň 🤍.txt"),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(filters=(StringUnicodeNormalizeFilter(normal_form="NFKC"),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("\r\n  \f\t\v   /home////test//žáｄｎý.txt \n\n", b'/home/test/\xc5\xbe\xc3\xa1dn\xc3\xbd.txt'.decode("utf-8")),
        (b'\r\n  \f\t\v   /home////test//\xc5\xbe\xc3\xa1\xef\xbd\x84\xef\xbd\x8e\xc3\xbd.txt \n\n'.decode("utf-8"), b'/home/test/\xc5\xbe\xc3\xa1dn\xc3\xbd.txt'.decode("utf-8")),
        (b'\r\n  \f\t\v   /home////test//\xc5\xbe\xc3\xa1\xef\xbd\x84\xef\xbd\x8e\xc3\xbd.txt \n\n'.decode("utf-8"), b'/home/test/\xc5\xbe\xc3\xa1dn\xc3\xbd.txt'.decode("utf-8")),
        (b'\r\n  \f\t\v   /home////test//z\xcc\x8ca\xcc\x81\xef\xbd\x84\xef\xbd\x8ey\xcc\x81.txt \n\n'.decode("utf-8"), b'/home/test/\xc5\xbe\xc3\xa1dn\xc3\xbd.txt'.decode("utf-8")),
        (b'\r\n  \f\t\v   /home////test//\xc5\xbe\xc3\xa1dn\xc3\xbd.txt \n\n'.decode("utf-8"), b'/home/test/\xc5\xbe\xc3\xa1dn\xc3\xbd.txt'.decode("utf-8")),
        (b'\r\n  \f\t\v   /home////test//z\xcc\x8ca\xcc\x81dny\xcc\x81.txt \n\n'.decode("utf-8"), b'/home/test/\xc5\xbe\xc3\xa1dn\xc3\xbd.txt'.decode("utf-8")),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(filters=(StringUnifyWhitespaceFilter(replacement_whitespace=" "),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("    \tfile.txt  \r\n", "file.txt"),
        ("    \tPříliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš žluťoučký kůň 🤍.txt  \r\n", "/home/test/Příliš žluťoučký kůň 🤍.txt"),
        ("    \tfi\r\nle.txt  \r\n", "fi  le.txt"),
        ("    \tPříliš\n\ržluťoučký\nkůň\t\v\f\u202f\u00a0🤍.txt  \r\n", "Příliš  žluťoučký kůň     🤍.txt"),
        ("    \t///home\u2028\x85//\x1d\x1c\u2029test/ \t/file.txt  \r\n", "/home  /   test/  /file.txt"),
        ("    \t///home//test/Příliš          žluťoučký \t\t \r\n kůň  🤍.txt  \r\n", "/home/test/Příliš          žluťoučký       kůň  🤍.txt"),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(validators=(UnixFilesystemPathContainsOnlyFilenameValidator(),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("\t\t\n  testfile.txt\u2029\x85", "testfile.txt"),
        ("\t\t\n  test\uffff.txt\u2029\x85", "test\uffff.txt"),
        ("\t\t\n  Příliš žluťoučký kůň.txt\u2029\x85", "Příliš žluťoučký kůň.txt"),
        ("\t\t\n  Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", "Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt"),
        ("\t\t\n  file 🤍.txt\u2029\x85", "file 🤍.txt"),
        ("\t\t\n  dir/testfile.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir/test\uffff.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir/Příliš žluťoučký kůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir/Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir/file 🤍.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir///testfile.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir///test\uffff.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir///Příliš žluťoučký kůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir///Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir///file 🤍.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ./testfile.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ./test\uffff.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ./Příliš žluťoučký kůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ./Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ./file 🤍.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  /home/test/dir/testfile.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  /home/test/dir/test\uffff.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  /home/test/dir/Příliš žluťoučký kůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  /home/test/dir/Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  /home/test/dir/file 🤍.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ///home/////test/dir//testfile.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ///home/////test/dir//test\uffff.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ///home/////test/dir//Příliš žluťoučký kůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ///home/////test/dir//Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ///home/////test/dir//file 🤍.txt\u2029\x85", DataValidationFailedExc),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(validators=(UnixFilesystemPathIsAbsoluteValidator(),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("\t\t\n  testfile.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  test\uffff.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  Příliš žluťoučký kůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  file 🤍.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir/testfile.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir/test\uffff.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir/Příliš žluťoučký kůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir/Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir/file 🤍.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir///testfile.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir///test\uffff.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir///Příliš žluťoučký kůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir///Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  dir///file 🤍.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ./testfile.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ./test\uffff.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ./Příliš žluťoučký kůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ./Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ./file 🤍.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  /home/test/dir/testfile.txt\u2029\x85", "/home/test/dir/testfile.txt"),
        ("\t\t\n  /home/test/dir/test\uffff.txt\u2029\x85", "/home/test/dir/test\uffff.txt"),
        ("\t\t\n  /home/test/dir/Příliš žluťoučký kůň.txt\u2029\x85", "/home/test/dir/Příliš žluťoučký kůň.txt"),
        ("\t\t\n  /home/test/dir/Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", "/home/test/dir/Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt"),
        ("\t\t\n  /home/test/dir/file 🤍.txt\u2029\x85", "/home/test/dir/file 🤍.txt"),
        ("\t\t\n  ///home/////test/dir//testfile.txt\u2029\x85", "/home/test/dir/testfile.txt"),
        ("\t\t\n  ///home/////test/dir//test\uffff.txt\u2029\x85", "/home/test/dir/test\uffff.txt"),
        ("\t\t\n  ///home/////test/dir//Příliš žluťoučký kůň.txt\u2029\x85", "/home/test/dir/Příliš žluťoučký kůň.txt"),
        ("\t\t\n  ///home/////test/dir//Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", "/home/test/dir/Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt"),
        ("\t\t\n  ///home/////test/dir//file 🤍.txt\u2029\x85", "/home/test/dir/file 🤍.txt"),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(validators=(UnixFilesystemPathIsRelativeValidator(),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("\t\t\n  testfile.txt\u2029\x85", "testfile.txt"),
        ("\t\t\n  test\uffff.txt\u2029\x85", "test\uffff.txt"),
        ("\t\t\n  Příliš žluťoučký kůň.txt\u2029\x85", "Příliš žluťoučký kůň.txt"),
        ("\t\t\n  Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", "Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt"),
        ("\t\t\n  file 🤍.txt\u2029\x85", "file 🤍.txt"),
        ("\t\t\n  dir/testfile.txt\u2029\x85", "dir/testfile.txt"),
        ("\t\t\n  dir/test\uffff.txt\u2029\x85", "dir/test\uffff.txt"),
        ("\t\t\n  dir/Příliš žluťoučký kůň.txt\u2029\x85", "dir/Příliš žluťoučký kůň.txt"),
        ("\t\t\n  dir/Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", "dir/Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt"),
        ("\t\t\n  dir/file 🤍.txt\u2029\x85", "dir/file 🤍.txt"),
        ("\t\t\n  dir///testfile.txt\u2029\x85", "dir/testfile.txt"),
        ("\t\t\n  dir///test\uffff.txt\u2029\x85", "dir/test\uffff.txt"),
        ("\t\t\n  dir///Příliš žluťoučký kůň.txt\u2029\x85", "dir/Příliš žluťoučký kůň.txt"),
        ("\t\t\n  dir///Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", "dir/Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt"),
        ("\t\t\n  dir///file 🤍.txt\u2029\x85", "dir/file 🤍.txt"),
        ("\t\t\n  ./testfile.txt\u2029\x85", "./testfile.txt"),
        ("\t\t\n  ./test\uffff.txt\u2029\x85", "./test\uffff.txt"),
        ("\t\t\n  ./Příliš žluťoučký kůň.txt\u2029\x85", "./Příliš žluťoučký kůň.txt"),
        ("\t\t\n  ./Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", "./Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt"),
        ("\t\t\n  ./file 🤍.txt\u2029\x85", "./file 🤍.txt"),
        ("\t\t\n  /home/test/dir/testfile.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  /home/test/dir/test\uffff.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  /home/test/dir/Příliš žluťoučký kůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  /home/test/dir/Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  /home/test/dir/file 🤍.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ///home/////test/dir//testfile.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ///home/////test/dir//test\uffff.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ///home/////test/dir//Příliš žluťoučký kůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ///home/////test/dir//Příliš\x85\x01\x02\x03  žluťoučký\t\fkůň.txt\u2029\x85", DataValidationFailedExc),
        ("\t\t\n  ///home/////test/dir//file 🤍.txt\u2029\x85", DataValidationFailedExc),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(validators=(SequenceMinimumLengthValidator(5),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("\n\n\n  t  \t\t", DataValidationFailedExc),
        ("\n\n\n  test  \t\t", DataValidationFailedExc),
        ("\n\n\n  test1  \t\t", "test1"),
        ("\n\n\n  test12  \t\t", "test12"),
        ("\n\n\n  test1234567890  \t\t", "test1234567890"),
        ("\n\n\n  /l.o  \t\t", DataValidationFailedExc),
        ("\n\n\n  /li.o  \t\t", "/li.o"),
        ("\n\n\n  /lib.o  \t\t", "/lib.o"),
        ("\n\n\n  ///////////l.o  \t\t", DataValidationFailedExc),
        ("\n\n\n  ///////////li.o  \t\t", "/li.o"),
        ("\n\n\n  ///////////lib.o  \t\t", "/lib.o"),
        ("\n\n\n  ///////////řřř  \t\t", DataValidationFailedExc),
        ("\n\n\n  ///////////řřřř  \t\t", "/řřřř"),
        ("\n\n\n  ///////////řřřřř  \t\t", "/řřřřř"),
        ("\n\n\n  ///////////🤍🤍🤍  \t\t", DataValidationFailedExc),
        ("\n\n\n  ///////////🤍🤍🤍🤍  \t\t", "/🤍🤍🤍🤍"),
        ("\n\n\n  ///////////🤍🤍🤍🤍🤍  \t\t", "/🤍🤍🤍🤍🤍"),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(validators=(SequenceMaximumLengthValidator(10),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("\r\r\n  a.txt  \t\v\u2029", "a.txt"),
        ("\r\r\n  test1.txt  \t\v\u2029", "test1.txt"),
        ("\r\r\n  test12.txt  \t\v\u2029", "test12.txt"),
        ("\r\r\n  test123.txt  \t\v\u2029", DataValidationFailedExc),
        ("\r\r\n  test1234567890.txt  \t\v\u2029", DataValidationFailedExc),
        ("\r\r\n  ////////////t.txt  \t\v\u2029", "/t.txt"),
        ("\r\r\n  ////////////test.txt  \t\v\u2029", "/test.txt"),
        ("\r\r\n  ////////////test1.txt  \t\v\u2029", "/test1.txt"),
        ("\r\r\n  ////////////test12.txt  \t\v\u2029", DataValidationFailedExc),
        ("\r\r\n  ////////////test1234567890.txt  \t\v\u2029", DataValidationFailedExc),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(validators=(StringContainsNoControlOrSeparatorCharactersValidator(allowed_characters=" "),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("    \tfile.txt  \r\n", "file.txt"),
        ("    \tPříliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš žluťoučký kůň 🤍.txt  \r\n", "/home/test/Příliš žluťoučký kůň 🤍.txt"),
        ("    \tfi\uffffle.txt  \r\n", DataValidationFailedExc),
        ("    \t\uffffPříliš žluťoučký kůň 🤍.txt  \r\n", DataValidationFailedExc),
        ("    \t///home//test/file.txt\uffff  \r\n", DataValidationFailedExc),
        ("    \t///home//test/Příliš\uffff žluťoučký kůň\uffff🤍.txt  \r\n", DataValidationFailedExc),
        ("    \tfi\n\rle.txt  \r\n", DataValidationFailedExc),
        ("    \t\n\rPříliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt\n\r  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš\n\r žluťoučký kůň\n\r🤍.txt  \r\n", DataValidationFailedExc),
        ("    \tfi\ale.txt  \r\n", DataValidationFailedExc),
        ("    \t\aPříliš žluťoučký kůň 🤍.txt  \r\n", DataValidationFailedExc),
        ("    \t///home//test/file.txt\a  \r\n", DataValidationFailedExc),
        ("    \t///home//test/Příliš\a žluťoučký kůň\a🤍.txt  \r\n", DataValidationFailedExc),
        ("    \tfi\u2060le.txt  \r\n", DataValidationFailedExc),
        ("    \t\u2060Příliš žluťoučký kůň 🤍.txt  \r\n", DataValidationFailedExc),
        ("    \t///home//test/file.txt\u2060  \r\n", DataValidationFailedExc),
        ("    \t///home//test/Příliš\u2060 žluťoučký kůň\u2060🤍.txt  \r\n", DataValidationFailedExc),
        ("    \tfi\u2028le.txt  \r\n", DataValidationFailedExc),
        ("    \t\u2028Příliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt\u2028  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš\u2028 žluťoučký kůň\u2028🤍.txt  \r\n", DataValidationFailedExc),
        ("    \tfi\u2029le.txt  \r\n", DataValidationFailedExc),
        ("    \t\u2029Příliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt\u2029  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš\u2029 žluťoučký kůň\u2029🤍.txt  \r\n", DataValidationFailedExc),
        ("    \tfi\u00a0le.txt  \r\n", DataValidationFailedExc),
        ("    \t\u00a0Příliš žluťoučký kůň 🤍.txt  \r\n", "Příliš žluťoučký kůň 🤍.txt"),
        ("    \t///home//test/file.txt\u00a0  \r\n", "/home/test/file.txt"),
        ("    \t///home//test/Příliš\u00a0 žluťoučký kůň\u00a0🤍.txt  \r\n", DataValidationFailedExc),
        ("    \tfi\x01le.txt  \r\n", DataValidationFailedExc),
        ("    \t\x01Příliš žluťoučký kůň 🤍.txt  \r\n", DataValidationFailedExc),
        ("    \t///home//test/file.txt\x01  \r\n", DataValidationFailedExc),
        ("    \t///home//test/Příliš\x01 žluťoučký kůň\x01🤍.txt  \r\n", DataValidationFailedExc),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(validators=(StringIsOnlySingleLineValidator(),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("\r\n     testfile.txt   \n\n", "testfile.txt"),
        ("\r\n     test\ufffffile.txt   \n\n", "test\ufffffile.txt"),
        ("\r\n     Příliš žluťoučký kůň.txt   \n\n", "Příliš žluťoučký kůň.txt"),
        ("\r\n     test🤍file.txt   \n\n", "test🤍file.txt"),
        ("\r\n     Příliš\tžluťoučký\t   kůň.txt   \n\n", "Příliš\tžluťoučký\t   kůň.txt"),
        ("\r\n     test🤍\t  file.txt   \n\n", "test🤍\t  file.txt"),
        ("\r\n     test\nfile.txt   \n\n", DataValidationFailedExc),
        ("\r\n     test\ufffffile\r.txt   \n\n", DataValidationFailedExc),
        ("\r\n     Příliš\r\nžluťoučký kůň.txt   \n\n", DataValidationFailedExc),
        ("\r\n     test\f🤍file.txt   \n\n", DataValidationFailedExc),
        ("\r\n     test\vfile.txt   \n\n", DataValidationFailedExc),
        ("\r\n     test\ufffffile\x1c.txt   \n\n", DataValidationFailedExc),
        ("\r\n     Příliš\x1džluťoučký kůň.txt   \n\n", DataValidationFailedExc),
        ("\r\n     test\x1e🤍file.txt   \n\n", DataValidationFailedExc),
        ("\r\n     test\x85file.txt   \n\n", DataValidationFailedExc),
        ("\r\n     test\ufffffile\u2028.txt   \n\n", DataValidationFailedExc),
        ("\r\n     Příliš\u2029žluťoučký kůň.txt   \n\n", DataValidationFailedExc),
        ("\r\n     dir////testfile.txt   \n\n", "dir/testfile.txt"),
        ("\r\n     dir////test\ufffffile.txt   \n\n", "dir/test\ufffffile.txt"),
        ("\r\n     dir////Příliš žluťoučký kůň.txt   \n\n", "dir/Příliš žluťoučký kůň.txt"),
        ("\r\n     dir////test🤍file.txt   \n\n", "dir/test🤍file.txt"),
        ("\r\n     dir////Příliš\tžluťoučký\t   kůň.txt   \n\n", "dir/Příliš\tžluťoučký\t   kůň.txt"),
        ("\r\n     dir////test🤍\t  file.txt   \n\n", "dir/test🤍\t  file.txt"),
        ("\r\n     dir////test\nfile.txt   \n\n", DataValidationFailedExc),
        ("\r\n     dir////test\ufffffile\r.txt   \n\n", DataValidationFailedExc),
        ("\r\n     dir////Příliš\r\nžluťoučký kůň.txt   \n\n", DataValidationFailedExc),
        ("\r\n     dir////test\f🤍file.txt   \n\n", DataValidationFailedExc),
        ("\r\n     dir////test\vfile.txt   \n\n", DataValidationFailedExc),
        ("\r\n     dir////test\ufffffile\x1c.txt   \n\n", DataValidationFailedExc),
        ("\r\n     dir////Příliš\x1džluťoučký kůň.txt   \n\n", DataValidationFailedExc),
        ("\r\n     dir////test\x1e🤍file.txt   \n\n", DataValidationFailedExc),
        ("\r\n     dir////test\x85file.txt   \n\n", DataValidationFailedExc),
        ("\r\n     dir////test\ufffffile\u2028.txt   \n\n", DataValidationFailedExc),
        ("\r\n     dir////Příliš\u2029žluťoučký kůň.txt   \n\n", DataValidationFailedExc),
        ("\r\n     //home///test/dir/////testfile.txt   \n\n", "/home/test/dir/testfile.txt"),
        ("\r\n     //home///test/dir/////test\ufffffile.txt   \n\n", "/home/test/dir/test\ufffffile.txt"),
        ("\r\n     //home///test/dir/////Příliš žluťoučký kůň.txt   \n\n", "/home/test/dir/Příliš žluťoučký kůň.txt"),
        ("\r\n     //home///test/dir/////test🤍file.txt   \n\n", "/home/test/dir/test🤍file.txt"),
        ("\r\n     //home///test/dir/////Příliš\tžluťoučký\t   kůň.txt   \n\n", "/home/test/dir/Příliš\tžluťoučký\t   kůň.txt"),
        ("\r\n     //home///test/dir/////test🤍\t  file.txt   \n\n", "/home/test/dir/test🤍\t  file.txt"),
        ("\r\n     //home///test/dir/////test\nfile.txt   \n\n", DataValidationFailedExc),
        ("\r\n     //home///test/dir/////test\ufffffile\r.txt   \n\n", DataValidationFailedExc),
        ("\r\n     //home///test/dir/////Příliš\r\nžluťoučký kůň.txt   \n\n", DataValidationFailedExc),
        ("\r\n     //home///test/dir/////test\f🤍file.txt   \n\n", DataValidationFailedExc),
        ("\r\n     //home///test/dir/////test\vfile.txt   \n\n", DataValidationFailedExc),
        ("\r\n     //home///test/dir/////test\ufffffile\x1c.txt   \n\n", DataValidationFailedExc),
        ("\r\n     //home///test/dir/////Příliš\x1džluťoučký kůň.txt   \n\n", DataValidationFailedExc),
        ("\r\n     //home///test/dir/////test\x1e🤍file.txt   \n\n", DataValidationFailedExc),
        ("\r\n     //home///test/dir/////test\x85file.txt   \n\n", DataValidationFailedExc),
        ("\r\n     //home///test/dir/////test\ufffffile\u2028.txt   \n\n", DataValidationFailedExc),
        ("\r\n     //home///test/dir/////Příliš\u2029žluťoučký kůň.txt   \n\n", DataValidationFailedExc),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
    (UnixFilesystemPathBlueprint(validators=(StringMatchesRegexValidator(r'^[0-9a-z_-]{1,20}\.(jpg|jpeg|png|gif)\Z', regex_compile_flags=re.IGNORECASE),)), (
        ("", InvalidInputDataExc),
        ("\t\n", InvalidInputDataExc),
        ("\x00", InvalidInputDataExc),
        ("test\x00file.txt", InvalidInputDataExc),
        ("\r   test\x00file.txt \t\n", InvalidInputDataExc),
        ("/home/test/test\x00file.txt", InvalidInputDataExc),
        ("\r   /home/test/test\x00file.txt \t\n", InvalidInputDataExc),
        ("\r\n   test_01-01.jpg  \t\f\u2029", "test_01-01.jpg"),
        ("\r\n   Test_01-01.Jpg  \t\f\u2029", "Test_01-01.Jpg"),
        ("\r\n   TEST_01-01.JPG  \t\f\u2029", "TEST_01-01.JPG"),
        ("\r\n   test_01-01.jpeg  \t\f\u2029", "test_01-01.jpeg"),
        ("\r\n   Test_01-01.Jpeg  \t\f\u2029", "Test_01-01.Jpeg"),
        ("\r\n   TEST_01-01.JPEG  \t\f\u2029", "TEST_01-01.JPEG"),
        ("\r\n   test_01-01.png  \t\f\u2029", "test_01-01.png"),
        ("\r\n   Test_01-01.Png  \t\f\u2029", "Test_01-01.Png"),
        ("\r\n   TEST_01-01.PNG  \t\f\u2029", "TEST_01-01.PNG"),
        ("\r\n   test_01-01.gif  \t\f\u2029", "test_01-01.gif"),
        ("\r\n   Test_01-01.Gif  \t\f\u2029", "Test_01-01.Gif"),
        ("\r\n   TEST_01-01.GIF  \t\f\u2029", "TEST_01-01.GIF"),
        ("\r\n   test_01-01.bmp  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test_01-01.Bmp  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST_01-01.BMP  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   test_01-01.txt  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test_01-01.Txt  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST_01-01.TXT  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   tešt_01-01.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Tešt_01-01.Jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEŠT_01-01.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   test_01-01jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test_01-01Jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST_01-01JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   test_01-01..jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test_01-01..Jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST_01-01..JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   test🤍_01-01.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test🤍_01-01.Jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST🤍_01-01.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   test _01-01.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test _01-01.Jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST _01-01.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   test\n_01-01.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test\n_01-01.Jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST\n_01-01.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   test\x01_01-01.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test\x01_01-01.Jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST\x01_01-01.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   test\uffff_01-01.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test\uffff_01-01.Jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST\uffff_01-01.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   test._01-01.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test._01-01.Jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST._01-01.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   test!_01-01.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test!_01-01.Jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST!_01-01.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   .  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   test_01-01.  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   Test_01-01.  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   TEST_01-01.  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   .jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   .Jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   .JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   a.jpg  \t\f\u2029", "a.jpg"),
        ("\r\n   aaaaaaaaaaaaaaaaaaa.jpg  \t\f\u2029", "aaaaaaaaaaaaaaaaaaa.jpg"),
        ("\r\n   aaaaaaaaaaaaaaaaaaaa.jpg  \t\f\u2029", "aaaaaaaaaaaaaaaaaaaa.jpg"),
        ("\r\n   aaaaaaaaaaaaaaaaaaaaa.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   A.JPG  \t\f\u2029", "A.JPG"),
        ("\r\n   AAAAAAAAAAAAAAAAAAA.JPG  \t\f\u2029", "AAAAAAAAAAAAAAAAAAA.JPG"),
        ("\r\n   AAAAAAAAAAAAAAAAAAAA.JPG  \t\f\u2029", "AAAAAAAAAAAAAAAAAAAA.JPG"),
        ("\r\n   AAAAAAAAAAAAAAAAAAAAA.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   dir/a.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   dir/A.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   dir///a.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   dir///A.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   /home/x/dir/a.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   /home/x/dir/A.JPG  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   ///home/x//dir////a.jpg  \t\f\u2029", DataValidationFailedExc),
        ("\r\n   ///home/x//dir////A.JPG  \t\f\u2029", DataValidationFailedExc),
        (None, InputDataTypeNotInAllowlistExc),
        (theoretical_testutils.EmptyObject(), InputDataTypeNotInAllowlistExc),
    )),
)


@pytest.mark.parametrize(("blueprint", "input_", "output"), theoretical_testutils.test_function_parameter_generator(__UNIX_FILESYSTEM_PATH_TEST_SUITE))
def test_unix_filesystem_path_blueprint(blueprint, input_, output):
    theoretical_testutils.perform_test(blueprint, input_, output)


def test_unix_filesystem_path_blueprint_filter_and_validator_sequences():
    filter_seq = (
        UnixFilesystemPathAddTrailingSlashFilter(),
        UnixFilesystemPathStripTrailingSlashesFilter(),
        StringControlAndSeparatorCharacterFilter(),
        StringDeduplicateWhitespaceFilter(),
        StringUnicodeNormalizeFilter(),
        StringUnifyWhitespaceFilter()
    )
    validator_seq = (
        UnixFilesystemPathContainsOnlyFilenameValidator(),
        UnixFilesystemPathIsAbsoluteValidator(),
        UnixFilesystemPathIsRelativeValidator(),
        SequenceMinimumLengthValidator(5),
        SequenceMaximumLengthValidator(10),
        StringContainsNoControlOrSeparatorCharactersValidator(),
        StringIsOnlySingleLineValidator(),
        StringMatchesRegexValidator(r'^[0-9]+\Z')
    )
    bp = UnixFilesystemPathBlueprint(filters=filter_seq, validators=validator_seq)

    assert (bp.get_filters() == filter_seq) and (bp.get_validators() == validator_seq)
